// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AlternativeTitle,
    Chapter,
    Config,
    LatestManga,
    Manga,
    MangaStatus,
    MangaWithAlt,
    ScrapingRule
} from "./models.js";
