// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AlternativeTitle {
    "id": number;
    "manga_id": number;
    "alternative_title": string;
    "created_at": string;

    /** Creates a new AlternativeTitle instance. */
    constructor($$source: Partial<AlternativeTitle> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("manga_id" in $$source)) {
            this["manga_id"] = 0;
        }
        if (!("alternative_title" in $$source)) {
            this["alternative_title"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlternativeTitle instance from a string or object.
     */
    static createFrom($$source: any = {}): AlternativeTitle {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlternativeTitle($$parsedSource as Partial<AlternativeTitle>);
    }
}

export class Chapter {
    "id": number;
    "manga_id": number;
    "chapter_number": number;
    "chapter_title": string;
    "volume": number;
    "translator_group": string;
    "language": string;
    "release_time_ts": number;
    "release_time_raw": string;

    /**
     * 0 or 1
     */
    "status_read": number;
    "path": string;

    /**
     * 0 or 1
     */
    "is_compressed": number;

    /**
     * valid, missing, corrupted
     */
    "status": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Chapter instance. */
    constructor($$source: Partial<Chapter> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("manga_id" in $$source)) {
            this["manga_id"] = 0;
        }
        if (!("chapter_number" in $$source)) {
            this["chapter_number"] = 0;
        }
        if (!("chapter_title" in $$source)) {
            this["chapter_title"] = "";
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("translator_group" in $$source)) {
            this["translator_group"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("release_time_ts" in $$source)) {
            this["release_time_ts"] = 0;
        }
        if (!("release_time_raw" in $$source)) {
            this["release_time_raw"] = "";
        }
        if (!("status_read" in $$source)) {
            this["status_read"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("is_compressed" in $$source)) {
            this["is_compressed"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Chapter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chapter($$parsedSource as Partial<Chapter>);
    }
}

export class Config {
    "Key": string;
    "Value": string;
    "CreatedAt": number;
    "UpdatedAt": number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = 0;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class Manga {
    "id": number;
    "main_title": string;
    "description": string;
    "year": number;
    "status_id": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Manga instance. */
    constructor($$source: Partial<Manga> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("main_title" in $$source)) {
            this["main_title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("status_id" in $$source)) {
            this["status_id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manga instance from a string or object.
     */
    static createFrom($$source: any = {}): Manga {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manga($$parsedSource as Partial<Manga>);
    }
}

export class MangaStatus {
    "id": number;
    "name": string;

    /** Creates a new MangaStatus instance. */
    constructor($$source: Partial<MangaStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MangaStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MangaStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MangaStatus($$parsedSource as Partial<MangaStatus>);
    }
}

export class ScrapingRule {
    "id": number;
    "site_key": string;
    "name": string;
    "domains_json": string;
    "website_url": string;
    "manga_rule_json": string;
    "chapter_rule_json": string;
    "enabled": number;
    "priority": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ScrapingRule instance. */
    constructor($$source: Partial<ScrapingRule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("site_key" in $$source)) {
            this["site_key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("domains_json" in $$source)) {
            this["domains_json"] = "";
        }
        if (!("website_url" in $$source)) {
            this["website_url"] = "";
        }
        if (!("manga_rule_json" in $$source)) {
            this["manga_rule_json"] = "";
        }
        if (!("chapter_rule_json" in $$source)) {
            this["chapter_rule_json"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = 0;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrapingRule instance from a string or object.
     */
    static createFrom($$source: any = {}): ScrapingRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScrapingRule($$parsedSource as Partial<ScrapingRule>);
    }
}
