// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService menangani operasi scraping menggunakan browser headless
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cleanup menutup browser saat aplikasi berhenti
 */
export function Cleanup(): $CancellablePromise<void> {
    return $Call.ByID(3141534450);
}

/**
 * ScrapePage melakukan scraping sederhana pada halaman web
 * url: Alamat web yang akan discrape
 * selector: CSS selector untuk elemen yang ingin diambil teksnya (opsional)
 */
export function ScrapePage(url: string, selector: string): $CancellablePromise<$models.ScrapeResult> {
    return $Call.ByID(3652988189, url, selector).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Screenshot mengambil screenshot halaman
 */
export function Screenshot(url: string): $CancellablePromise<string> {
    return $Call.ByID(663554766, url);
}

// Private type creation functions
const $$createType0 = $models.ScrapeResult.createFrom;
