// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

/**
 * AddAlternativeTitle adds an alternative title to a manga
 */
export function AddAlternativeTitle(mangaID: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(3946793451, mangaID, title);
}

export function BatchCreateChapters(chapters: models$0.Chapter[]): $CancellablePromise<void> {
    return $Call.ByID(3314965793, chapters);
}

export function BatchCreateManga(mangas: models$0.Manga[]): $CancellablePromise<void> {
    return $Call.ByID(493328281, mangas);
}

/**
 * CheckStatusMangaByTitle checks if a manga with the given title exists.
 */
export function CheckStatusMangaByTitle(title: string): $CancellablePromise<[boolean, number]> {
    return $Call.ByID(2765024448, title);
}

export function CreateChapter(chapter: models$0.Chapter): $CancellablePromise<number> {
    return $Call.ByID(1456305318, chapter);
}

/**
 * CreateManga adds a new manga to the library with validation
 */
export function CreateManga(manga: models$0.Manga): $CancellablePromise<number> {
    return $Call.ByID(2444566759, manga);
}

export function DeleteChapter(id: number): $CancellablePromise<void> {
    return $Call.ByID(1743669335, id);
}

export function DeleteManga(id: number): $CancellablePromise<void> {
    return $Call.ByID(2064937506, id);
}

export function DeleteScrapingRule(siteKey: string): $CancellablePromise<void> {
    return $Call.ByID(79211419, siteKey);
}

/**
 * GetAllMangaStatuses retrieves all available manga statuses
 */
export function GetAllMangaStatuses(): $CancellablePromise<models$0.MangaStatus[]> {
    return $Call.ByID(1818255672).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAlternativeTitles retrieves all alternative titles for a manga
 */
export function GetAlternativeTitles(mangaID: number): $CancellablePromise<models$0.AlternativeTitle[]> {
    return $Call.ByID(4270703793, mangaID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetChapter(id: number): $CancellablePromise<models$0.Chapter | null> {
    return $Call.ByID(3460386756, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetChaptersByMangaID(mangaID: number): $CancellablePromise<models$0.Chapter[]> {
    return $Call.ByID(3439105553, mangaID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetConfig retrieves a configuration object by key
 */
export function GetConfig(key: string): $CancellablePromise<models$0.Config | null> {
    return $Call.ByID(684324977, key).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetConfigValue retrieves just the value string for a given key
 */
export function GetConfigValue(key: string): $CancellablePromise<string> {
    return $Call.ByID(2834813662, key);
}

/**
 * GetLatestManga returns the latest updated manga
 */
export function GetLatestManga(): $CancellablePromise<models$0.LatestManga[]> {
    return $Call.ByID(2834965160).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetManga retrieves a manga by its ID
 */
export function GetManga(id: number): $CancellablePromise<models$0.Manga | null> {
    return $Call.ByID(3262083485, id).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetMangaDetail returns a manga with its alternative titles and chapters
 */
export function GetMangaDetail(id: number): $CancellablePromise<models$0.MangaDetail | null> {
    return $Call.ByID(2810622860, id).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetMangaWithAlternativeTitles returns a manga with its alternative titles
 */
export function GetMangaWithAlternativeTitles(id: number): $CancellablePromise<models$0.MangaWithAlt | null> {
    return $Call.ByID(2965412675, id).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetScrapingRule(siteKey: string): $CancellablePromise<models$0.ScrapingRule | null> {
    return $Call.ByID(2300776374, siteKey).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListManga(limit: number, offset: number): $CancellablePromise<models$0.Manga[]> {
    return $Call.ByID(3312694067, limit, offset).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ListScrapingRules(): $CancellablePromise<models$0.ScrapingRule[]> {
    return $Call.ByID(2931394105).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ListScrapingRulesBasic(): $CancellablePromise<models$0.ScrapingRule[]> {
    return $Call.ByID(4162381753).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * MarkChapterAsRead updates the chapter status_read to true
 */
export function MarkChapterAsRead(chapterID: number): $CancellablePromise<void> {
    return $Call.ByID(3517251945, chapterID);
}

/**
 * SaveManga inserts a new manga if it doesn't exist, or retrieves the existing one.
 * Returns the manga ID and a boolean indicating if it was newly inserted (true) or retrieved (false).
 */
export function SaveManga(manga: models$0.Manga): $CancellablePromise<[number, boolean]> {
    return $Call.ByID(36930252, manga);
}

export function SaveScrapingRule(rule: models$0.ScrapingRule): $CancellablePromise<void> {
    return $Call.ByID(1443302969, rule);
}

/**
 * ScanDirectoryForManga scans the given directory for manga and chapters
 */
export function ScanDirectoryForManga(mangasDir: string): $CancellablePromise<void> {
    return $Call.ByID(1101106334, mangasDir);
}

/**
 * SetConfig sets a configuration value for a given key
 */
export function SetConfig(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2728594373, key, value);
}

export function UpdateChapter(chapter: models$0.Chapter): $CancellablePromise<void> {
    return $Call.ByID(931699349, chapter);
}

export function UpdateManga(manga: models$0.Manga): $CancellablePromise<void> {
    return $Call.ByID(3401058728, manga);
}

// Private type creation functions
const $$createType0 = models$0.MangaStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.AlternativeTitle.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.Chapter.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType4);
const $$createType7 = models$0.Config.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = models$0.LatestManga.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = models$0.Manga.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = models$0.MangaDetail.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = models$0.MangaWithAlt.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = models$0.ScrapingRule.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $Create.Array($$createType11);
const $$createType20 = $Create.Array($$createType17);
