// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService handles file downloading operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadImages downloads a list of images to the specified output directory
 * It uses an adaptive downloader engine to manage concurrency
 */
export function DownloadImages(urls: string[], outputDir: string, options: $models.DownloadOptions | null): $CancellablePromise<void> {
    return $Call.ByID(2527980206, urls, outputDir, options);
}
