// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService handles file operations for manga
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ConvertToCbz converts a directory to a .cbz file and deletes the original directory.
 */
export function ConvertToCbz(dirPath: string): $CancellablePromise<void> {
    return $Call.ByID(2916049733, dirPath);
}

/**
 * DeleteImages deletes specific image files from a directory or a cbz/zip archive.
 * It prioritizes: Directory > .cbz > .zip
 * relativePath: path relative to the manga directory (e.g. "MangaTitle/Chapter1")
 * filenames: list of filenames (basenames) to delete.
 */
export function DeleteImages(relativePath: string, filenames: string[]): $CancellablePromise<void> {
    return $Call.ByID(3820987783, relativePath, filenames);
}

/**
 * GetImageList returns a list of image files in a directory or cbz/zip archive.
 * It prioritizes: Directory > .cbz > .zip
 * relativePath: path relative to the manga directory (e.g. "MangaTitle/Chapter1")
 */
export function GetImageList(relativePath: string): $CancellablePromise<string[]> {
    return $Call.ByID(808358535, relativePath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetMangaDir(): $CancellablePromise<string> {
    return $Call.ByID(2831883277);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
