// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConvertBatchToWebP(inputPaths: string[], outputDir: string, options: $models.WebPConvertOptions | null): $CancellablePromise<$models.WebPBatchResult[]> {
    return $Call.ByID(3937515777, inputPaths, outputDir, options).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ConvertSingleToWebP(inputPath: string, outputPath: string, options: $models.WebPConvertOptions | null): $CancellablePromise<string> {
    return $Call.ByID(4053388733, inputPath, outputPath, options);
}

// Private type creation functions
const $$createType0 = $models.WebPBatchResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
