// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ScrapeResult menyimpan hasil scraping
 */
export class ScrapeResult {
    "title": string;
    "content": string;
    "images": string[];
    "error"?: string;

    /** Creates a new ScrapeResult instance. */
    constructor($$source: Partial<ScrapeResult> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrapeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ScrapeResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField2_0($$parsedSource["images"]);
        }
        return new ScrapeResult($$parsedSource as Partial<ScrapeResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
